---
name: Svobodní Praha 12
locales: [cs]
subdomain: praha12
domains: [praha12.svobodni.cz, www.praha12.svobodni.cz]
seo_title: Svobodní Praha 12
meta_keywords: Svobodní Praha 12
meta_description: Strana svobodných občanů
timezone: Prague
