---
name: Svobodní Praha 12
locales: [cs]
subdomain: praha12
domains: [praha12.svobodni.cz]
seo_title: Svobodní Praha 12
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
