---
name: Svobodní Vimperk
locales: [cs]
subdomain: vimperk
domains: [www.vimperk.svobodni.cz, vimperk.svobodni.cz]
meta_keywords: svobodni, vimperk, politika, volby
meta_description: 'Svobodní kandidují v komunálních volbách 2014 ve Vimperku. Svobodně
  a férově. '
timezone: Prague
