---
name: Svobodní Vimperk
locales: [cs]
subdomain: vimperk
domains: [vimperk.svobodni.cz, www.vimperk.svobodni.cz]
seo_title: Svobodní Vimperk
meta_keywords: Svobodní Vimperk
meta_description: Strana svobodných občanů
timezone: Prague
