---
name: Svobodní Mutěnice
locales: [cs]
subdomain: mutenice
domains: [www.mutenice.svobodni.cz, mutenice.svobodni.cz]
seo_title: Svobodní Mutěnice
meta_keywords: Svobodní, Mutěnice
meta_description: Web příznivců Strany svobodných občanů (Svobodní) v Mutěnicích.
timezone: Prague
