---
name: Svobodní Mutěnice
locales: [cs]
subdomain: mutenice
domains: [mutenice.svobodni.cz, www.mutenice.svobodni.cz]
seo_title: Svobodní Mutěnice
meta_keywords: Svobodní Mutěnice
meta_description: Strana svobodných občanů
timezone: Prague
