---
name: Svobodní Česká Lípa
locales: [cs]
subdomain: ceskalipa
domains: [www.ceskalipa.svobodni.cz, ceskalipa.svobodni.cz]
seo_title: Svobodní Česká Lípa
meta_keywords: Svobodní Česká Lípa
meta_description: Strana svobodných občanů
timezone: Prague
