---
name: Svobodní Hradec Králové
locales: [cs]
subdomain: hk
domains: [hk.svobodni.cz]
seo_title: Svobodní
meta_keywords: Svobodní, komunální volby 2104, Hradec Králové, Strana svobodných občanů
meta_description: Svobodní Hradec Králové - komunální volby 2014
timezone: Prague
