---
name: Svobodní Hradec Králové
locales: [cs]
subdomain: hk
domains: [hk.svobodni.cz, www.hk.svobodni.cz]
seo_title: Svobodní Hradec Králové
meta_keywords: Svobodní Hradec Králové
meta_description: Strana svobodných občanů
timezone: Prague
