---
name: Svobodní Bílina
locales: [cs]
subdomain: bilina
domains: [bilina.svobodni.cz]
seo_title: Svobodní Bílina
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
