---
name: Svobodní Praha 6
locales: [cs]
subdomain: praha6
domains: [www.praha6.svobodni.cz, praha6.svobodni.cz]
seo_title: Svobodní Praha 6
meta_keywords: Svobodní Praha 6
meta_description: Strana svobodných občanů
timezone: Prague
