---
name: Svobodní Brno - Střed
locales: [cs]
subdomain: stred
domains: [stred.svobodni.cz, www.stred.svobodni.cz]
seo_title: Svobodní Brno - Střed
meta_keywords: Svobodní Brno - Střed
meta_description: Strana svobodných občanů
timezone: Prague
