---
name: Svobodní Praha 21
locales: [cs]
subdomain: praha21
domains: [praha21.svobodni.cz, www.praha21.svobodni.cz]
seo_title: Svobodní Praha 21
meta_keywords: Svobodní Praha 21
meta_description: Strana svobodných občanů
timezone: Prague
