---
name: Svobodní Praha 21
locales: [cs]
subdomain: praha21
domains: [praha21.svobodni.cz]
seo_title: Svobodní Praha 21
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
