---
name: Svobodní Otrokovice
locales: [cs]
subdomain: otrokovice
domains: [otrokovice.svobodni.cz, www.otrokovice.svobodni.cz]
seo_title: Svobodní Otrokovice
meta_keywords: Svobodní Otrokovice
meta_description: Strana svobodných občanů
timezone: Prague
