---
name: Svobodní Otrokovice
locales: [cs]
subdomain: otrokovice
domains: [otrokovice.svobodni.cz]
seo_title: Svobodní Otrokovice
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
