---
name: Svobodní Praha 18 - Letňany
locales: [cs]
subdomain: letnany
domains: [www.letnany.svobodni.cz, letnany.svobodni.cz]
seo_title: Svobodní Praha 18 - Letňany
meta_keywords: Svobodní Praha 18 - Letňany
meta_description: Strana svobodných občanů
timezone: Prague
