---
name: Svobodní Praha 18 - Letňany
locales: [cs]
subdomain: letnany
domains: [letnany.svobodni.cz]
seo_title: Svobodní Praha 18 - Letňany
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
