---
name: Svobodní Jindřichohradecko
locales: [cs]
subdomain: jh
domains: [www.jh.svobodni.cz, jh.svobodni.cz]
seo_title: Svobodní Jindřichohradecko
meta_keywords: Svobodní Jindřichohradecko
meta_description: Strana svobodných občanů
timezone: Prague
