---
name: Svobodní Zlín
locales: [cs]
subdomain: zlin
domains: [www.zlin.svobodni.cz, zlin.svobodni.cz]
seo_title: Svobodní Zlín
meta_keywords: Svobodní Zlín, moderní město, Svobodní, Zlín
meta_description: Volební web Strany svobodných občanů ve Zlíně do komunálních voleb
  v roce 2014
timezone: Prague
