---
name: Svobodní Zlín
locales: [cs]
subdomain: zlin
domains: [zlin.svobodni.cz, www.zlin.svobodni.cz]
seo_title: Svobodní Zlín
meta_keywords: Svobodní Zlín
meta_description: Strana svobodných občanů
timezone: Prague
