---
name: Svobodní Hořice
locales: [cs]
subdomain: horice
domains: [www.horice.svobodni.cz, horice.svobodni.cz]
seo_title: Svobodní Hořice
meta_keywords: Svobodní Hořice
meta_description: Strana svobodných občanů
timezone: Prague
