---
name: Svobodní Brandýs nad Labem - Stará Boleslav
locales: [cs]
subdomain: brandys-boleslav
domains: [brandys-boleslav.svobodni.cz, www.brandys-boleslav.svobodni.cz]
seo_title: Svobodní Brandýs nad Labem - Stará Boleslav
meta_keywords: Svobodní Brandýs nad Labem - Stará Boleslav
meta_description: Strana svobodných občanů
timezone: Prague
