---
name: Svobodní Napajedla
locales: [cs]
subdomain: napajedla
domains: [www.napajedla.svobodni.cz, napajedla.svobodni.cz]
seo_title: Svobodní Napajedla
meta_keywords: Svobodní Napajedla
meta_description: Strana svobodných občanů
timezone: Prague
