---
name: Petr Zavadil
locales: [cs]
subdomain: zavadil
domains: [zavadil.svobodni.cz, www.zavadil.svobodni.cz]
seo_title: Petr Zavadil
meta_keywords: Petr Zavadil
meta_description: Strana svobodných občanů
timezone: Prague
