---
name: Petr Zavadil - Mělník
locales: [cs]
subdomain: zavadil
domains: [zavadil.svobodni.cz, www.zavadil.svobodni.cz]
seo_title: Petr Zavadil - Mělník
meta_keywords: Petr Zavadil - Mělník
meta_description: Strana svobodných občanů
timezone: Prague
