---
name: Svobodní Velké Meziříčí
locales: [cs]
subdomain: velkemezirici
domains: [www.velkemezirici.svobodni.cz, velkemezirici.svobodni.cz]
seo_title: Svobodní Velké Meziříčí
meta_keywords: Svobodní Velké Meziříčí
meta_description: Strana svobodných občanů
timezone: Prague
