---
name: Svobodní Velké Meziříčí
locales: [cs]
subdomain: velkemezirici
domains: [www.velkemezirici.svobodni.cz, velkemezirici.svobodni.cz]
seo_title: Svobodní Velké Meziříčí
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
