---
name: Svobodní Praha 17
locales: [cs]
subdomain: praha17
domains: [praha17.svobodni.cz]
seo_title: Svobodní Praha 17 - Řepy
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
