---
name: Svobodní Lysá nad Labem
locales: [cs]
subdomain: lysanadlabem
domains: [www.lysanadlabem.svobodni.cz, lysanadlabem.svobodni.cz]
seo_title: Svobodní Lysá nad Labem
meta_keywords: Svobodní Lysá nad Labem
meta_description: Strana svobodných občanů
timezone: Prague
