---
name: Svobodní Tábor
locales: [cs]
subdomain: tabor
domains: [www.tabor.svobodni.cz, tabor.svobodni.cz]
seo_title: Svobodní Tábor
meta_keywords: Svobodní Tábor
meta_description: Strana svobodných občanů
timezone: Prague
