---
name: Svobodní Brno-Slatina
locales: [cs]
subdomain: brno-slatina
domains: [www.brno-slatina.svobodni.cz, brno-slatina.svobodni.cz]
seo_title: Svobodní Brno-Slatina
meta_keywords: Svobodní Brno-Slatina
meta_description: Strana svobodných občanů
timezone: Prague
