---
name: Svobodní Praha 22
locales: [cs]
subdomain: praha22
domains: [www.praha22.svobodni.cz, praha22.svobodni.cz]
seo_title: Svobodní Praha 22
meta_keywords: Svobodní Praha 22
meta_description: Strana svobodných občanů
timezone: Prague
