---
name: Svobodní Ostrožská Nová Ves
locales: [cs]
subdomain: onves
domains: [onves.svobodni.cz, www.onves.svobodni.cz]
seo_title: Svobodní Ostrožská Nová Ves
meta_keywords: Svobodní Ostrožská Nová Ves
meta_description: Strana svobodných občanů
timezone: Prague
