---
name: Svobodní Velký Osek
locales: [cs]
subdomain: velkyosek
domains: [velkyosek.svobodni.cz]
seo_title: Svobodní Velký Osek
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
