---
name: Svobodní Velký Osek
locales: [cs]
subdomain: velkyosek
domains: [www.velkyosek.svobodni.cz, velkyosek.svobodni.cz]
seo_title: Svobodní Velký Osek
meta_keywords: Svobodní Velký Osek
meta_description: Strana svobodných občanů
timezone: Prague
