---
name: MUDr. Karel Beneš
locales: [cs]
subdomain: benes
domains: [www.benes.svobodni.cz, benes.svobodni.cz]
seo_title: MUDr. Karel Beneš
meta_keywords: MUDr. Karel Beneš
meta_description: Strana svobodných občanů
timezone: Prague
