---
name: Svobodní Praha 10
locales: [cs]
subdomain: praha10
domains: [www.praha10.svobodni.cz, praha10.svobodni.cz]
seo_title: Svobodní Praha 10
meta_keywords: Svobodní Praha 10
meta_description: Strana svobodných občanů
timezone: Prague
