---
name: Svobodní Ostrava
locales: [cs]
subdomain: ostrava
domains: [www.ostrava.svobodni.cz, ostrava.svobodni.cz]
seo_title: Svobodní Ostrava
meta_keywords: Svobodní Ostrava
meta_description: Strana svobodných občanů
timezone: Prague
