---
name: Svobodní Jablůnka
locales: [cs]
subdomain: jablunka
domains: [www.jablunka.svobodni.cz, jablunka.svobodni.cz]
seo_title: Svobodní Jablůnka
meta_keywords: Svobodní Jablůnka
meta_description: Strana svobodných občanů
timezone: Prague
