---
name: Svobodní Nová Ves v Horách
locales: [cs]
subdomain: novavesvhorach
domains: [novavesvhorach.svobodni.cz, www.novavesvhorach.svobodni.cz]
seo_title: Svobodní Nová Ves v Horách
meta_keywords: Svobodní Nová Ves v Horách
meta_description: Strana svobodných občanů
timezone: Prague
