---
name: Svobodní Ústí nad Labem
locales: [cs]
subdomain: usti
domains: [www.usti.svobodni.cz, usti.svobodni.cz]
seo_title: Svobodní Ústí nad Labem
meta_keywords: Svobodní Ústí nad Labem
meta_description: Strana svobodných občanů
timezone: Prague
