---
name: Svobodní Ústí nad Labem
locales: [cs]
subdomain: usti
domains: [usti.svobodni.cz]
seo_title: Svobodní Ústí nad Labem
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
