---
name: Svobodní Brno - Líšeň
locales: [cs]
subdomain: lisen
domains: [www.lisen.svobodni.cz, lisen.svobodni.cz]
seo_title: Svobodní Brno - Líšeň
meta_keywords: Svobodní Brno - Líšeň
meta_description: Strana svobodných občanů
timezone: Prague
