---
name: Svobodní Brno
locales: [cs]
subdomain: brno
domains: [brno.svobodni.cz, www.brno.svobodni.cz]
seo_title: Svobodní Brno
meta_keywords: Svobodní Brno
meta_description: Strana svobodných občanů
timezone: Prague
