---
name: Svobodní Šumperk
locales: [cs]
subdomain: sumperk
domains: [sumperk.svobodni.cz, www.sumperk.svobodni.cz]
seo_title: Svobodní Šumperk
meta_keywords: Svobodní Šumperk
meta_description: Strana svobodných občanů
timezone: Prague
