---
name: Svobodní Jihlava
locales: [cs]
subdomain: jihlava
domains: [jihlava.svobodni.cz, www.jihlava.svobodni.cz]
seo_title: Svobodní Jihlava
meta_keywords: Svobodní Jihlava
meta_description: Strana svobodných občanů
timezone: Prague
