---
name: Svobodní Mladá Boleslav
locales: [cs]
subdomain: mladaboleslav
domains: [mb.svobodni.cz, mboleslav.svobodni.cz, www.mb.svobodni.cz, www.mboleslav.svobodni.cz,
  www.mladaboleslav.svobodni.cz, mladaboleslav.svobodni.cz]
timezone: Prague
