---
name: Svobodní Mladá Boleslav
locales: [cs]
subdomain: mladaboleslav
domains: [mladaboleslav.svobodni.cz, www.mladaboleslav.svobodni.cz]
seo_title: Svobodní Mladá Boleslav
meta_keywords: Svobodní Mladá Boleslav
meta_description: Strana svobodných občanů
timezone: Prague
