---
name: Svobodní Mladá Boleslav
locales: [cs]
subdomain: mladaboleslav
domains: [mladaboleslav.svobodni.cz]
seo_title: Svobodní Mladá Boleslav
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
