---
name: Svobodní Praha 3
locales: [cs]
subdomain: praha3
domains: [www.praha3.svobodni.cz, praha3.svobodni.cz]
seo_title: Svobodní
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
