---
name: Svobodní Pardubice
locales: [cs]
subdomain: pardubice
domains: [www.pardubice.svobodni.cz, pardubice.svobodni.cz]
seo_title: Svobodní Pardubice
meta_keywords: Svobodní Pardubice
meta_description: Strana svobodných občanů
timezone: Prague
