---
name: Svobodní Kolín
locales: [cs]
subdomain: kolin
domains: [www.kolin.svobodni.cz, kolin.svobodni.cz]
seo_title: Svobodní Kolín
meta_keywords: Svobodní Kolín
meta_description: Strana svobodných občanů
timezone: Prague
