---
name: Svobodní Nový Bydžov
locales: [cs]
subdomain: novybydzov
domains: [novybydzov.svobodni.cz, www.novybydzov.svobodni.cz]
seo_title: Svobodní Nový Bydžov
meta_keywords: Svobodní Nový Bydžov
meta_description: Strana svobodných občanů
timezone: Prague
