---
name: Svobodní Nový Bydžov
locales: [cs]
subdomain: novybydzov
domains: [nb.svobodni.cz, novybydzov.svobodni.cz]
seo_title: Svobodní Nový Bydžov
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
