---
name: Ing. Vladimír Gregor - Děčín
locales: [cs]
subdomain: gregor
domains: [gregor.svobodni.cz, www.gregor.svobodni.cz]
seo_title: Ing. Vladimír Gregor - Děčín
meta_keywords: Ing. Vladimír Gregor - Děčín
meta_description: Strana svobodných občanů
timezone: Prague
