---
name: Svobodní Praha 4
locales: [cs]
subdomain: praha4
domains: [www.praha4.svobodni.cz, praha4.svobodni.cz]
seo_title: Svobodní Praha 4
meta_keywords: Svobodní, Strana svobodných občanů, politika, strana, politická strana,
  svoboda, Praha, Praha 4, komunální volby, komunál, SSO
meta_description: Oficiální stránka pobočky Strany svobodných občanů v městské části
  Praha 4
timezone: Prague
