---
name: Svobodní Praha 4
locales: [cs]
subdomain: praha4
domains: [praha4.svobodni.cz]
seo_title: Svobodní Praha 4
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
