---
name: Svobodní Praha 1
locales: [cs]
subdomain: praha1
domains: [www.praha1.svobodni.cz, praha1.svobodni.cz]
seo_title: Svobodní Praha 1
meta_keywords: Svobodní Praha 1
meta_description: Strana svobodných občanů
timezone: Prague
