---
name: RNDr. Jiří Payne
locales: [cs]
subdomain: payne
domains: [payne.svobodni.cz, www.payne.svobodni.cz]
seo_title: RNDr. Jiří Payne
meta_keywords: RNDr. Jiří Payne
meta_description: Strana svobodných občanů
timezone: Prague
