---
name: Svobodní Česká Lípa
locales: [cs]
subdomain: lipa
domains: [lipa.svobodni.cz, www.lipa.svobodni.cz]
seo_title: Svobodní Česká Lípa
meta_keywords: Svobodní Česká Lípa
meta_description: Strana svobodných občanů
timezone: Prague
