---
name: Svobodní Přestanov
locales: [cs]
subdomain: prestanov
domains: [prestanov.svobodni.cz]
seo_title: Svobodní Přestanov
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
