---
name: Svobodní Přestanov
locales: [cs]
subdomain: prestanov
domains: [www.prestanov.svobodni.cz, prestanov.svobodni.cz]
seo_title: Svobodní Přestanov
meta_keywords: Svobodní Přestanov
meta_description: Strana svobodných občanů
timezone: Prague
