---
name: Svobodní Malá Morava
locales: [cs]
subdomain: malamorava
domains: [malamorava.svobodni.cz, www.malamorava.svobodni.cz]
seo_title: Svobodní Malá Morava
meta_keywords: Svobodní Malá Morava
meta_description: Strana svobodných občanů
timezone: Prague
