---
name: Svobodní Žatec
locales: [cs]
subdomain: zatec
domains: [www.zatec.svobodni.cz, zatec.svobodni.cz]
seo_title: Svobodní Žatec
meta_keywords: Svobodní Žatec
meta_description: Strana svobodných občanů
timezone: Prague
