---
name: Svobodní Jeseník
locales: [cs]
subdomain: jesenik
domains: [www.jesenik.svobodni.cz, jesenik.svobodni.cz]
seo_title: Svobodní Jeseník
meta_keywords: Svobodní Jeseník
meta_description: Strana svobodných občanů
timezone: Prague
