---
name: Svobodní Turnov
locales: [cs]
subdomain: turnov
seo_title: Strana svobodných občanů - Turnov
meta_keywords: Strana svobodných občanů - Turnov, Svobodní, Turnov, politika, Maskovka,
  doprava, cesky raj, Ulicny, Simunkova, Brustmann, Paickr
meta_description: Strana svobodných občanů - Turnov
domains: [turnov.svobodni.cz, www.turnov.svobodni.cz]
timezone: Prague
