---
name: Svobodní Turnov
locales: [cs]
subdomain: turnov
domains: [www.turnov.svobodni.cz, turnov.svobodni.cz]
seo_title: Strana svobodných občanů - Turnov
meta_keywords: Strana svobodných občanů - Turnov, Svobodní, Turnov, politika, Maskovka,
  doprava, cesky raj, Ulicny, Simunkova, Brustmann, Paickr
meta_description: Strana svobodných občanů - Turnov
timezone: Prague
