---
name: Svobodní Roudnice
locales: [cs]
subdomain: roudnice
domains: [www.roudnice.svobodni.cz, roudnice.svobodni.cz]
seo_title: Svobodní Roudnice
meta_keywords: Svobodní Roudnice
meta_description: Strana svobodných občanů
timezone: Prague
