---
name: Svobodní Jablonec nad Nisou
locales: [cs]
subdomain: jablonec
domains: [www.jablonec.svobodni.cz, jablonec.svobodni.cz]
seo_title: Svobodní Jablonec nad Nisou
meta_keywords: Svobodní Jablonec nad Nisou
meta_description: Strana svobodných občanů
timezone: Prague
