---
name: Svobodní Brno-sever
locales: [cs]
subdomain: brno-sever
domains: [www.brno-sever.svobodni.cz, brno-sever.svobodni.cz]
seo_title: Svobodní Brno-sever
meta_keywords: Svobodní Brno-sever
meta_description: Strana svobodných občanů
timezone: Prague
