---
name: Svobodní Řevnice
locales: [cs]
subdomain: revnice
domains: [revnice.svobodni.cz, www.revnice.svobodni.cz]
seo_title: Svobodní Řevnice
meta_keywords: Svobodní Řevnice
meta_description: Strana svobodných občanů
timezone: Prague
