---
name: Svobodní Řevnice
locales: [cs]
subdomain: revnice
domains: [www.revnice.svobodni.cz, revnice.svobodni.cz]
seo_title: Svobodní Řevnice
meta_keywords: Svobodní Řevnice
meta_description: Strana svobodných občanů
timezone: Prague
