---
name: Svobodní Praha 2
locales: [cs]
subdomain: praha2
domains: [www.praha2.svobodni.cz, praha2.svobodni.cz]
seo_title: Svobodní Praha 2
meta_keywords: Svobodní Praha 2
meta_description: Strana svobodných občanů
timezone: Prague
