---
name: Svobodní Zábřeh
locales: [cs]
subdomain: zabreh
domains: [www.zabreh.svobodni.cz, zabreh.svobodni.cz]
seo_title: Svobodní Zábřeh
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
