---
name: Svobodní Praha 5
locales: [cs]
subdomain: praha5
domains: [www.praha5.svobodni.cz, praha5.svobodni.cz]
seo_title: Svobodní Praha 5
meta_keywords: Svobodní Praha 5
meta_description: Strana svobodných občanů
timezone: Prague
