---
name: Svobodní Praha 13
locales: [cs]
subdomain: praha13
domains: [www.praha13.svobodni.cz, praha13.svobodni.cz]
seo_title: Svobodní Praha 13
meta_keywords: Svobodní Praha 13
meta_description: Strana svobodných občanů
timezone: Prague
