---
name: Svobodní Praha 13
locales: [cs]
subdomain: praha13
domains: [praha13.svobodni.cz]
seo_title: Svobodní Praha 13
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
