---
name: Svobodní Praha 13
locales: [cs]
subdomain: praha13
domains: [praha13.svobodni.cz, www.praha13.svobodni.cz]
seo_title: Svobodní Praha 13
meta_keywords: Svobodní Praha 13
meta_description: Strana svobodných občanů
timezone: Prague
