---
name: Svobodní Děčín
locales: [cs]
subdomain: decin
domains: [decin.svobodni.cz, www.decin.svobodni.cz]
seo_title: Svobodní Děčín
meta_keywords: Svobodní Děčín
meta_description: Strana svobodných občanů
timezone: Prague
