---
name: Svobodní Slaný
locales: [cs]
subdomain: slany
domains: [www.slany.svobodni.cz, slany.svobodni.cz]
seo_title: Svobodní Slaný
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
