---
name: Svobodní Kohoutovice
locales: [cs]
subdomain: kohoutovice
domains: [kohoutovice.svobodni.cz, www.kohoutovice.svobodni.cz]
seo_title: Svobodní Kohoutovice
meta_keywords: Svobodní Kohoutovice
meta_description: Strana svobodných občanů
timezone: Prague
