---
name: Svobodní Kohoutovice
locales: [cs]
subdomain: kohoutovice
domains: [kohoutovice.svobodni.cz]
seo_title: Svobodní Kohoutovice
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
