---
name: Svobodní Praha 14
locales: [cs]
subdomain: praha14
domains: [www.praha14.svobodni.cz, praha14.svobodni.cz]
seo_title: Svobodní Praha 14
meta_keywords: Svobodní Praha 14
meta_description: Strana svobodných občanů
timezone: Prague
