---
name: Svobodní Sokolov
locales: [cs]
subdomain: sokolov
domains: [www.sokolov.svobodni.cz, sokolov.svobodni.cz]
seo_title: Svobodní Sokolov
meta_keywords: Svobodní Sokolov
meta_description: Strana svobodných občanů
timezone: Prague
