---
name: Svobodní Chrudim
locales: [cs]
subdomain: chrudim
domains: [chrudim.svobodni.cz, www.chrudim.svobodni.cz]
seo_title: Svobodní Chrudim
meta_keywords: Svobodní Chrudim
meta_description: Strana svobodných občanů
timezone: Prague
