---
name: Svobodní Říčany
locales: [cs]
subdomain: ricany
domains: [www.ricany.svobodni.cz, ricany.svobodni.cz]
seo_title: Svobodní Říčany
meta_keywords: Svobodní Říčany
meta_description: Strana svobodných občanů
timezone: Prague
