---
name: Svobodní Praha 11
locales: [cs]
subdomain: praha11
domains: [praha11.svobodni.cz]
seo_title: Svobodní Praha 11
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
