---
name: Svobodní Hodonín
locales: [cs]
subdomain: hodonin
domains: [www.hodonin.svobodni.cz, hodonin.svobodni.cz]
seo_title: Svobodní Hodonín
meta_keywords: some meta keywords
meta_description: some meta description
timezone: Prague
