---
name: Svobodní Týniště
locales: [cs]
subdomain: tyniste
domains: [www.tyniste.svobodni.cz, tyniste.svobodni.cz]
seo_title: Svobodní Týniště
meta_keywords: Svobodní Týniště
meta_description: Strana svobodných občanů
timezone: Prague
