---
name: Svobodní Semily
locales: [cs]
subdomain: semily
domains: [www.semily.svobodni.cz, semily.svobodni.cz]
seo_title: Svobodní Semily
meta_keywords: Svobodní Semily
meta_description: Strana svobodných občanů
timezone: Prague
