---
name: Svobodní Vsetín
locales: [cs]
subdomain: vsetin
domains: [www.vsetin.svobodni.cz, vsetin.svobodni.cz]
seo_title: Svobodní Vsetín
meta_keywords: Svobodní Vsetín
meta_description: Strana svobodných občanů
timezone: Prague
