---
name: Svobodní Praha 7
locales: [cs]
subdomain: praha7
domains: [www.praha7.svobodni.cz, praha7.svobodni.cz]
seo_title: Svobodní Praha 7
meta_keywords: Svobodní Praha 7
meta_description: Strana svobodných občanů
timezone: Prague
